name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: apt
      run: sudo apt update && sudo apt install libusb-1.0-0-dev libsqlite3-dev ninja-build
    - name: make
      run: make

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: brew
      run: brew install sqlite pkg-config libusb ninja
    - name: make
      run: make

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v1
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: pacman
      run: |
        pacman -S --noconfirm --needed make ninja mingw-w64-i686-libusb mingw-w64-i686-sqlite3 mingw-w64-i686-zlib mingw-w64-i686-gcc zip
    - name: build
      run: |
        make

