name: Autorelease

on:
  push:
    branches:
      - "master"

jobs:
  dev-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: pacman
      run: |
        pacman -S --noconfirm --needed make ninja mingw-w64-i686-libusb mingw-w64-i686-sqlite3 mingw-w64-i686-zlib mingw-w64-cross-gcc zip
    - name: build
      run: |
        make CXX=/opt/bin/i686-w64-mingw32-g++.exe AR="/opt/bin/i686-w64-mingw32-ar.exe rcs"
    - name: zip
      run: |
        zip -9 fluxengine.zip fluxengine.exe brother120tool.exe brother240tool.exe FluxEngine.cydsn/CortexM3/ARM_GCC_541/Release/FluxEngine.hex
    - name: tag
      uses: EndBug/latest-tag@latest
      with:
        tag-name: dev
        description: >
          This is an automatically built version of the FluxEngine Windows
          client which is generated whenever a significant checkin has
          happened. It's had no testing whatsoever. To use, download it, put it
          somewhere, and then run it from a cmd window or other command line
          shell.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    - name: delete-old-assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: dev
        assets: | 
          fluxengine.zip
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        name: Development build
        files: |
          fluxengine.zip
        tag_name: dev
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
